[package]
name = "titan"
version = "0.1.0"
authors = ["Toby Sullivan <tobyjsullivan@gmail.com>"]
edition = "2018"

[dependencies.sdl2]
version = "0.32"
default-features = false
features = ["gfx", "image", "unsafe_textures"]

[features]
unsafe_textures = []
